// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6aVRVf3262zUh0v2325sYrVZ8r4cMCo',
    appId: '1:639024428174:web:473c8c9382a4c141f3c5df',
    messagingSenderId: '639024428174',
    projectId: 'blockvault-investment-db251',
    authDomain: 'blockvault-investment-db251.firebaseapp.com',
    databaseURL: 'https://blockvault-investment-db251-default-rtdb.firebaseio.com',
    storageBucket: 'blockvault-investment-db251.appspot.com',
    measurementId: 'G-37QG3GVTVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKb-V9uV9czc2-tnGg7qKq7FJ5dyTtt9I',
    appId: '1:639024428174:android:b68de8b92f8c1f48f3c5df',
    messagingSenderId: '639024428174',
    projectId: 'blockvault-investment-db251',
    databaseURL: 'https://blockvault-investment-db251-default-rtdb.firebaseio.com',
    storageBucket: 'blockvault-investment-db251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwtP8eQloqSLlH2IrMjQetH6yJN_dwwl4',
    appId: '1:639024428174:ios:836c3723721a8f60f3c5df',
    messagingSenderId: '639024428174',
    projectId: 'blockvault-investment-db251',
    databaseURL: 'https://blockvault-investment-db251-default-rtdb.firebaseio.com',
    storageBucket: 'blockvault-investment-db251.appspot.com',
    iosClientId: '639024428174-ofmcldt3q117okpdoddb7jeuse5aft4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockvaultInvestmentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwtP8eQloqSLlH2IrMjQetH6yJN_dwwl4',
    appId: '1:639024428174:ios:836c3723721a8f60f3c5df',
    messagingSenderId: '639024428174',
    projectId: 'blockvault-investment-db251',
    databaseURL: 'https://blockvault-investment-db251-default-rtdb.firebaseio.com',
    storageBucket: 'blockvault-investment-db251.appspot.com',
    iosClientId: '639024428174-ofmcldt3q117okpdoddb7jeuse5aft4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockvaultInvestmentFlutter',
  );
}
